name: "Update repository packages"

on: 
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: "docker"
        uses: "docker://ghcr.io/rerigferl/vpm-repository-builder:latest"
        with:
          args: |
            "source.txt"
            "-r"
            ${{ github.token }}
      - run: |
          cat vpm.json
